version: "2.1"

services:

  rabbit_mq:

    image: rabbitmq:3-management-alpine
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
  app:
    build: musik
    depends_on:
        - rabbit_mq
    links: 
        - rabbit_mq
    environment:
        AMQP_URL_FROM_BOT: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./app:/src/app

  bot:
    build: telegram_bot
    depends_on:
        - rabbit_mq
    links: 
        - rabbit_mq
    environment:
        AMQP_URL_FROM_BOT: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./bot:/src/bot
volumes:
    rabbit_mqdata:
      driver: local